/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Lógica.Ejecutable;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Color;

public class nuevaD extends javax.swing.JFrame {
    int xMouse, yMouse;
    /**
     * Creates new form nuevaD
     */
    public nuevaD() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        backpanel1 = new javax.swing.JPanel();
        Regreso = new javax.swing.JLabel();
        helperfood = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitpanel = new javax.swing.JPanel();
        exitlabel = new javax.swing.JLabel();
        iniciosesion = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        alimento = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        Fecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(200, 100));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backpanel1.setBackground(new java.awt.Color(0, 134, 190));

        Regreso.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        Regreso.setForeground(new java.awt.Color(255, 255, 255));
        Regreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Regreso.setText("REGRESAR");
        Regreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegresoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backpanel1Layout = new javax.swing.GroupLayout(backpanel1);
        backpanel1.setLayout(backpanel1Layout);
        backpanel1Layout.setHorizontalGroup(
            backpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Regreso, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        backpanel1Layout.setVerticalGroup(
            backpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backpanel1Layout.createSequentialGroup()
                .addComponent(Regreso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(backpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 120, 40));

        helperfood.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        helperfood.setForeground(new java.awt.Color(255, 255, 255));
        helperfood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helperfood.setText("Helper Food");
        bg.add(helperfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 260, 40));

        icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/image/logo.png"))); // NOI18N
        bg.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 280, 150));

        fondo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/image/city.png"))); // NOI18N
        bg.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 280, 500));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitpanel.setBackground(new java.awt.Color(255, 255, 255));
        exitpanel.setPreferredSize(new java.awt.Dimension(40, 40));

        exitlabel.setBackground(new java.awt.Color(255, 255, 255));
        exitlabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        exitlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitlabel.setText("X");
        exitlabel.setToolTipText("");
        exitlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitlabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 760, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        iniciosesion.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        iniciosesion.setText("NUEVA DONACIONES");
        bg.add(iniciosesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 30));

        logo.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/image/favicon.png"))); // NOI18N
        logo.setText("HELPER FOOD");
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 220, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 270, 0));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Alimento");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 90, 20));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Cantidad");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 90, 20));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        jLabel3.setText("<html>Fecha de Caducidad");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jButton2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        bg.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));
        bg.add(alimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 210, -1));
        bg.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 210, -1));
        bg.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitlabelMouseClicked

    private void exitlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlabelMouseEntered
        exitpanel.setBackground(Color.red);
        exitlabel.setForeground(Color.white);
    }//GEN-LAST:event_exitlabelMouseEntered

    private void exitlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlabelMouseExited
        exitpanel.setBackground(Color.white);
        exitlabel.setForeground(Color.black);
    }//GEN-LAST:event_exitlabelMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void RegresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresoMouseExited
        backpanel1.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_RegresoMouseExited

    private void RegresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresoMouseEntered
        backpanel1.setBackground(new Color(0,170,255));
    }//GEN-LAST:event_RegresoMouseEntered

    private void RegresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresoMouseClicked
        Ejecutable.setBeneficiarioActivo(null);
        sesion inicioSesion = new sesion();
        inicioSesion.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Alimento = alimento.getText();
        String Cantidad = cantidad.getText();
        String Dia = Integer.toString(Fecha.getCalendar().get(Calendar.DAY_OF_MONTH));
        String Mes = Integer.toString(Fecha.getCalendar().get(Calendar.MONTH)+1);
        String Año = Integer.toString(Fecha.getCalendar().get(Calendar.YEAR));
        String fechaCaducidad = (Año+"-"+Mes+"-"+"-"+Dia);
        if(!Alimento.isEmpty()){
            if(!Cantidad.isEmpty()){
                if(!fechaCaducidad.isEmpty()){
                    try {
                        Ejecutable.crearDonacion(Alimento, Integer.parseInt(Cantidad), fechaCaducidad, Ejecutable.getDonanteActivo());
                        JOptionPane.showMessageDialog(null, "La donación se guardo con éxito");
                        MisDonaciones Donaciones = new MisDonaciones();
                        Donaciones.setVisible(true);
                        dispose();
                    } catch (IOException ex) {
                        Logger.getLogger(nuevaD.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(nuevaD.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "El campo de fecha de caducidad no se ha llenado");
                }
            }else{
                JOptionPane.showMessageDialog(null, "El campo de cantidad no se ha llenado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "El campo de alimento no se ha llenado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MisDonaciones Donaciones = new MisDonaciones();
        Donaciones.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevaD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevaD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JLabel Regreso;
    private javax.swing.JTextField alimento;
    private javax.swing.JPanel backpanel1;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel exitlabel;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel helperfood;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel iniciosesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
