package Interfaz;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.Color;
import javax.swing.JTextField;
import Lógica.Ejecutable;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class cuenta extends javax.swing.JFrame {
    int xMouse, yMouse;
    int tipoUsuario;
    String contrasena;
    String ubicacion;
    String contacto;
    /**
     * Creates new form cuenta
     */
    public cuenta() {
        initComponents();
        if(Ejecutable.getBeneficiarioActivo() != null){
            Long IDBeneficiario = Ejecutable.getBeneficiarioActivo();
            ID.setText(String.valueOf(IDBeneficiario));
            Contacto.setText(Ejecutable.getListaBeneficiarios().get(IDBeneficiario).getContacto());
            Ubicacion.setText(Ejecutable.getListaBeneficiarios().get(IDBeneficiario).getUbicacion());
            Beneficiario.setSelected(true);
            ID.setEditable(false);
            Contacto.setEditable(false);
            Ubicacion.setEditable(false);
            Beneficiario.setEnabled(false);
            Donador.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Por favor establece tu nueva contraseña");
        }
        if(Ejecutable.getDonanteActivo() != null){
            Long IDDonante = Ejecutable.getDonanteActivo();
            ID.setText(String.valueOf(IDDonante));
            Contacto.setText(Ejecutable.getListaDonantes().get(IDDonante).getContacto());
            Ubicacion.setText(Ejecutable.getListaDonantes().get(IDDonante).getUbicacion());
            Donador.setSelected(true);
            ID.setEditable(false);
            Contacto.setEditable(false);
            Ubicacion.setEditable(false);
            Beneficiario.setEnabled(false);
            Donador.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Por favor establece tu nueva contraseña");
        }
        
        Gbut.add(Donador);
        Gbut.add(Beneficiario);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gbut = new javax.swing.ButtonGroup();
        bgc = new javax.swing.JPanel();
        icono = new javax.swing.JLabel();
        helperfood = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitpanel = new javax.swing.JPanel();
        exitlabel = new javax.swing.JLabel();
        backpanel = new javax.swing.JPanel();
        backlabel = new javax.swing.JLabel();
        iniciosesion = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passlabel = new javax.swing.JLabel();
        Contrasena = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        loginpanel = new javax.swing.JPanel();
        loginlabel = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        Contacto = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        id2 = new javax.swing.JLabel();
        Ubicacion = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Beneficiario = new javax.swing.JRadioButton();
        Donador = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        bgc.setBackground(new java.awt.Color(255, 255, 255));
        bgc.setPreferredSize(new java.awt.Dimension(800, 500));
        bgc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/image/logo.png"))); // NOI18N
        bgc.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 280, 150));

        helperfood.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        helperfood.setForeground(new java.awt.Color(255, 255, 255));
        helperfood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helperfood.setText("Helper Food");
        bgc.add(helperfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 260, 40));

        fondo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/image/city.png"))); // NOI18N
        bgc.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 280, 500));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitpanel.setBackground(new java.awt.Color(255, 255, 255));
        exitpanel.setPreferredSize(new java.awt.Dimension(40, 40));

        exitlabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        exitlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitlabel.setText("X");
        exitlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitlabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 760, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgc.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        backpanel.setBackground(new java.awt.Color(0, 134, 190));

        backlabel.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        backlabel.setForeground(new java.awt.Color(255, 255, 255));
        backlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backlabel.setText("REGRESAR");
        backlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backlabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backpanelLayout = new javax.swing.GroupLayout(backpanel);
        backpanel.setLayout(backpanelLayout);
        backpanelLayout.setHorizontalGroup(
            backpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        backpanelLayout.setVerticalGroup(
            backpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgc.add(backpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 110, 40));

        iniciosesion.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        iniciosesion.setText("CREAR CUENTA");
        bgc.add(iniciosesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 200, 30));

        id.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        id.setText("IDENTIFICACIÓN");
        bgc.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 120, -1));

        ID.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        ID.setForeground(new java.awt.Color(204, 204, 204));
        ID.setText("Ingrese el número de identificación sin puntos ni comas");
        ID.setToolTipText("");
        ID.setBorder(null);
        ID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IDMousePressed(evt);
            }
        });
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        bgc.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 420, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bgc.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 420, 10));

        passlabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        passlabel.setText("CONTRASEÑA");
        bgc.add(passlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 110, 20));

        Contrasena.setForeground(new java.awt.Color(204, 204, 204));
        Contrasena.setText("********");
        Contrasena.setBorder(null);
        Contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ContrasenaMousePressed(evt);
            }
        });
        Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActionPerformed(evt);
            }
        });
        bgc.add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 420, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bgc.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 420, 10));

        loginpanel.setBackground(new java.awt.Color(0, 134, 190));

        loginlabel.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        loginlabel.setForeground(new java.awt.Color(255, 255, 255));
        loginlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginlabel.setText("REGISTRAR");
        loginlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginlabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginpanelLayout = new javax.swing.GroupLayout(loginpanel);
        loginpanel.setLayout(loginpanelLayout);
        loginpanelLayout.setHorizontalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        loginpanelLayout.setVerticalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bgc.add(loginpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, 40));

        id1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        id1.setText("CONTACTO");
        bgc.add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, -1));

        Contacto.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        Contacto.setForeground(new java.awt.Color(204, 204, 204));
        Contacto.setText("Ingrese número de contacto o alguna dirección");
        Contacto.setToolTipText("");
        Contacto.setBorder(null);
        Contacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ContactoMousePressed(evt);
            }
        });
        Contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactoActionPerformed(evt);
            }
        });
        bgc.add(Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 420, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bgc.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 420, 10));

        id2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        id2.setText("UBICACIÓN");
        bgc.add(id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 120, -1));

        Ubicacion.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        Ubicacion.setForeground(new java.awt.Color(204, 204, 204));
        Ubicacion.setText("Ingrese su ubicación");
        Ubicacion.setToolTipText("");
        Ubicacion.setBorder(null);
        Ubicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UbicacionMousePressed(evt);
            }
        });
        Ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbicacionActionPerformed(evt);
            }
        });
        bgc.add(Ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 420, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bgc.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 420, 10));

        Beneficiario.setText("Beneficiario");
        Beneficiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeneficiarioActionPerformed(evt);
            }
        });
        bgc.add(Beneficiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        Donador.setText("Donador");
        Donador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonadorActionPerformed(evt);
            }
        });
        bgc.add(Donador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("<html>Si perdiste tu contraseña vuelve a llenar los espacios con el mismo número de Identificación");
        bgc.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 430, 20));

        logo1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/image/favicon.png"))); // NOI18N
        logo1.setText("HELPER FOOD");
        bgc.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitlabelMouseClicked

    private void exitlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlabelMouseEntered
        exitpanel.setBackground(Color.red);
        exitlabel.setForeground(Color.white);
    }//GEN-LAST:event_exitlabelMouseEntered

    private void exitlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlabelMouseExited
        exitpanel.setBackground(Color.white);
        exitlabel.setForeground(Color.black);
    }//GEN-LAST:event_exitlabelMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);

    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void backlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabelMouseClicked
        principal paginaPrincipal = new principal();
        paginaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_backlabelMouseClicked

    private void backlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabelMouseEntered
        backpanel.setBackground(new Color(0,170,255));
    }//GEN-LAST:event_backlabelMouseEntered

    private void backlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabelMouseExited
        backpanel.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_backlabelMouseExited

    private void IDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDMousePressed
        if(ID.getText().equals("Ingrese el número de identificación sin puntos ni comas")){
            ID.setText("");
            ID.setForeground(Color.black);
        }
        if(String.valueOf(Contrasena.getPassword()).isEmpty()){
            Contrasena.setText("********");
            Contrasena.setForeground(Color.gray);
        }
        if(Contacto.getText().isEmpty()){
            Contacto.setText("Ingrese número de contacto o alguna dirección");
            Contacto.setForeground(Color.gray);
        }
        if(Ubicacion.getText().isEmpty()){
            Ubicacion.setText("Ingrese su ubicación");
            Ubicacion.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_IDMousePressed

    private void ContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContrasenaMousePressed
        if(ID.getText().isEmpty()){
            ID.setText("Ingrese el número de identificación sin puntos ni comas");
            ID.setForeground(Color.gray);
        }
        if(Contacto.getText().isEmpty()){
            Contacto.setText("Ingrese número de contacto o alguna dirección");
            Contacto.setForeground(Color.gray);
        }
        if(Ubicacion.getText().isEmpty()){
            Ubicacion.setText("Ingrese su ubicación");
            Ubicacion.setForeground(Color.gray);
        }
        
        if(String.valueOf(Contrasena.getPassword()).equals("********")){
            Contrasena.setText("");
            Contrasena.setForeground(Color.black);
        }
    }//GEN-LAST:event_ContrasenaMousePressed

    private void loginlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlabelMouseClicked
        contrasena = String.valueOf(Contrasena.getPassword());
        contacto = Contacto.getText();
        ubicacion = Ubicacion.getText();
        if (!ID.getText().equals("Ingrese el número de identificación sin puntos ni comas") && !ID.getText().isEmpty()){
            if (!contrasena.equals("********") && !contrasena.isEmpty()){
                if (!contacto.equals("Ingrese número de contacto o alguna dirección") && !contacto.isEmpty()){
                    if (!ubicacion.equals("Ingrese su ubicación") && !ubicacion.isEmpty()){
                        if(Ejecutable.getListaBeneficiarios().containsKey(Long.parseLong(ID.getText())) == false && Ejecutable.getListaDonantes().containsKey(Long.parseLong(ID.getText())) == false){
                            Ejecutable.crearUsuario(Long.parseLong(ID.getText()), contrasena, contacto, ubicacion, tipoUsuario);
                            principal paginaPrincipal = new principal();
                            paginaPrincipal.setVisible(true);
                            dispose();
                        }else{
                            if(Ejecutable.getBeneficiarioActivo() == null && Ejecutable.getDonanteActivo() == null){
                                JOptionPane.showMessageDialog(null, "El nombre de usuario ya se ha usado");  
                            }  
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "El campo de ubicación no se ha llenado");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "El campo de contacto no se ha llenado");
                }
            }else{
                JOptionPane.showMessageDialog(null, "El campo de contraseña no se ha llenado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "El campo de nombre no se ha llenado");
        }
        if (Ejecutable.getBeneficiarioActivo() != null || Ejecutable.getDonanteActivo() != null){
            Ejecutable.editarUsuario(Long.parseLong(ID.getText()), contrasena, contacto, ubicacion, tipoUsuario);
            JOptionPane.showMessageDialog(null, "La contraseña se ha guardado con éxito");
            principal paginaPrincipal = new principal();
            paginaPrincipal.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_loginlabelMouseClicked

    private void loginlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlabelMouseEntered
        loginpanel.setBackground(new Color(0,170,255));
    }//GEN-LAST:event_loginlabelMouseEntered

    private void loginlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlabelMouseExited
        loginpanel.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_loginlabelMouseExited

    private void ContactoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactoMousePressed
        if(ID.getText().isEmpty()){
            ID.setText("Ingrese el número de identificación sin puntos ni comas");
            ID.setForeground(Color.gray);
        }
        if(String.valueOf(Contrasena.getPassword()).isEmpty()){
            Contrasena.setText("********");
            Contrasena.setForeground(Color.gray);
        }
        if(Contacto.getText().equals("Ingrese número de contacto o alguna dirección")){
            Contacto.setText("");
            Contacto.setForeground(Color.black);
        }
        if(Ubicacion.getText().isEmpty()){
            Ubicacion.setText("Ingrese su ubicación");
            Ubicacion.setForeground(Color.gray);
        }    }//GEN-LAST:event_ContactoMousePressed

    private void UbicacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UbicacionMousePressed
        if(ID.getText().isEmpty()){
            ID.setText("Ingrese el número de identificación sin puntos ni comas");
            ID.setForeground(Color.gray);
        }
        if(String.valueOf(Contrasena.getPassword()).isEmpty()){
            Contrasena.setText("********");
            Contrasena.setForeground(Color.gray);
        }
        if(Contacto.getText().isEmpty()){
            Contacto.setText("Ingrese número de contacto o alguna dirección");
            Contacto.setForeground(Color.gray);
        }
        if(Ubicacion.getText().equals("Ingrese su ubicación")){
            Ubicacion.setText("");
            Ubicacion.setForeground(Color.black);
        }
    }//GEN-LAST:event_UbicacionMousePressed

    private void BeneficiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeneficiarioActionPerformed
        tipoUsuario = 2;
    }//GEN-LAST:event_BeneficiarioActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        
    }//GEN-LAST:event_IDActionPerformed

    private void ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActionPerformed

    }//GEN-LAST:event_ContrasenaActionPerformed

    private void ContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactoActionPerformed

    }//GEN-LAST:event_ContactoActionPerformed

    private void UbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbicacionActionPerformed

    }//GEN-LAST:event_UbicacionActionPerformed

    private void DonadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonadorActionPerformed
        tipoUsuario = 1;
    }//GEN-LAST:event_DonadorActionPerformed
    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Beneficiario;
    private javax.swing.JTextField Contacto;
    private javax.swing.JPasswordField Contrasena;
    private javax.swing.JRadioButton Donador;
    private javax.swing.ButtonGroup Gbut;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Ubicacion;
    private javax.swing.JLabel backlabel;
    private javax.swing.JPanel backpanel;
    private javax.swing.JPanel bgc;
    private javax.swing.JLabel exitlabel;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel helperfood;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel id;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel id2;
    private javax.swing.JLabel iniciosesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel loginlabel;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel passlabel;
    // End of variables declaration//GEN-END:variables
}
